const  quiz=[
	 
	{
		numb: 1,
		question:"ikinyabiziga cyose cyangwa ibinyabiziga bigendabigomba kugira?",
	   
		options:
		[ "umuyobozi","umuherekeza", "A na B ni ibisubizo byukuri", "Ntagisubizo cyukuri kirimo"],
	    
        answer:0
      
		
		
		
	
	},
	{
		
		numb: 2,
		question:"ijambo akayira bivuga inzira nyabagendwa ifunganye yagenewe gusa? ",
		
		options:
		[
		
		"Abanyamaguru",
        "Ibinyabiziga bigendera ku biziga bibiri" ,
		"A na B ni ibisubizo by'ukuri",

       "Ntagisubizo cy'ukuri kirimo"
		],
		answer:2
	},{
		
		numb: 3,
		question:"Umurongo uciyemo uduce umenyesha ahegereye umurongo ushobora kuzuzwa n'uturanga gukata tw'ibara ryera utwo turanga cyerekezo tumenyesha ?",
		
		options:
		[
			"Igisate cy'umuhanda abayobozi bagomba gukurikira" ,
		"Aherekeye umurongo ukomeje",
        "Igabanurwa ry'umubare w'ibisate by'umuhanda mu cyerekezo bajyamo",
      "A na C nibyo"
		],
		answer:2
	},
	{
		
		numb: 4,
		question:"Ahantu ho kugendera mu muhanda herekanwa n'ibimenyetso bimurika ibinyabiziga ntibishobora kuhagenda ?",
		answer: 3,
		options:
	[
	"Biteganye",
	"kumurongo umwe",
       "A na B nibyo",
	 "Ntagisubizo cy'ukuri kirimo"
	]
		
	},
];